# ============================
# Điều hướng Tính Chất Số
# ============================
print("Bài tập 1: Kiểm tra số nguyên tố")
print("Bài tập 2: Kiểm tra số hoàn hảo")
print("Bài tập 3: Kiểm tra số Armstrong")
print("Bài tập 4: Tính ước chung lớn nhất (GCD)")
print("Bài tập 5: Tính bội chung nhỏ nhất (LCM)")
print("Bài tập 6: Kiểm tra số đối xứng (Palindrome)")
print("Bài tập 7: Tính tổng các ước của số")
print("Bài tập 8: Kiểm tra số Fibonacci")
print("Bài tập 9: Kiểm tra số chính phương")
print("Bài tập 10: Tính số lượng chữ số trong một số")
print("Bài tập 11: Tính tổng các chữ số của số")
print("Bài tập 12: Kiểm tra số hoàn hảo")
print("Bài tập 13: Kiểm tra số chính phương")
print("Bài tập 14: Tính số lũy thừa")
print("Bài tập 15: Kiểm tra số khuyết thiếu")
print("Bài tập 16: Kiểm tra số nguyên tố Mersenne")
print("Bài tập 17: Kiểm tra số gần nguyên tố")
print("Bài tập 18: Kiểm tra số Armstrong")
print("Bài tập 19: Kiểm tra số hoán vị")
print("Bài tập 20: Kiểm tra số có tính đối xứng")
print("Bài tập 21: Kiểm tra số Lychrel")
print("Bài tập 22: Kiểm tra số thuộc dãy Fibonacci")
print("Bài tập 23: Tính phần tử tổng quát của dãy Fibonacci")
print("Bài tập 24: Tìm ước chung lớn nhất (Euclid Algorithm)")
print("Bài tập 25: Kiểm tra số Abundant")
print("Bài tập 26: Kiểm tra số Sphenic")
print("Bài tập 27: Tính bậc của số")
print("Bài tập 28: Kiểm tra số prime factor")
print("Bài tập 29: Kiểm tra số hạnh phúc")
print("Bài tập 30: Kiểm tra số bình phương hoàn chỉnh")
print("Bài tập 31: Tìm ước chung lớn nhất và bội chung nhỏ nhất")
print("Bài tập 32: Kiểm tra số Armstrong n chữ số")
print("Bài tập 33: Tính số nghịch đảo của một số")
print("Bài tập 34: Kiểm tra số strong")
print("Bài tập 35: Kiểm tra số Fibonacci")
print("Bài tập 36: Kiểm tra số kỳ lạ")
print("Bài tập 37: Tìm số nguyên tố nhỏ hơn n")
print("Bài tập 38: Tính tổng các số nguyên tố dưới n")
print("Bài tập 39: Kiểm tra số hợp số")
print("Bài tập 40: Kiểm tra số nguyên tố có phần tử khác")
print("Bài tập 41: Kiểm tra số phân kỳ")
print("Bài tập 42: Tìm số hoàn hảo nhỏ nhất lớn hơn n")
print("Bài tập 43: Kiểm tra số trong dãy Fibonacci")
print("Bài tập 44: Kiểm tra số hạnh phúc")
print("Bài tập 45: Kiểm tra số Amicable")
print("Bài tập 46: Tính số ước của số")
print("Bài tập 47: Kiểm tra số chính phương")
print("Bài tập 48: Kiểm tra số hoán vị số nguyên tố")
print("Bài tập 49: Kiểm tra số tối ưu")
print("Bài tập 50: Tính phần tử thứ n trong dãy Fibonacci")
print("Bài tập 51: Đổi số từ hệ thập phân sang nhị phân")
print("Bài tập 52: Đổi số từ hệ nhị phân sang thập phân")
print("Bài tập 53: Đổi số từ hệ thập phân sang hệ cơ số khác")
print("Bài tập 54: Đổi số từ hệ cơ số khác sang hệ thập phân")
print("\n======================================\n")